// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_USER_MENUS = 'FETCH_USER_MENUS'
export const FETCH_NAVIGATION = 'FETCH_NAVIGATION'
export const FETCH_USER_ROLES = 'FETCH_USER_ROLES'
export const FETCH_USER_PERMISSIONS = 'FETCH_USER_PERMISSIONS'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// leads.js
export const FETCH_LEADS = 'FETCH_LEADS'
export const FETCH_LEADS_NEEDS_ATTENTION = 'FETCH_LEADS_NEEDS_ATTENTION'
export const FETCH_LEADS_MY_LEADS = 'FETCH_LEADS_MY_LEADS'
export const SAVE_LEAD = 'SAVE_LEAD'
export const UPDATE_LEAD = 'UPDATE_LEAD'
export const EDIT_LEAD = 'EDIT_LEAD'
export const DELETE_LEAD = 'DELETE_LEAD'
export const UPDATED_ESCALATION = 'UPDATED_ESCALATION'
export const SHOW_MODAL = 'SHOW_MODAL'
export const SET_ORG_ID = 'SET_ORG_ID'
export const FETCH_LEAD_COMMENTS = 'FETCH_LEAD_COMMENTS'
export const ADD_LEAD_COMMENT = 'ADD_LEAD_COMMENT'
export const DELETE_LEAD_COMMENT = 'DELETE_LEAD_COMMENT'
export const EDIT_LEAD_COMMENT = 'EDIT_LEAD_COMMENT'

// leadhistory.js
export const GET_LEAD_HISTORY = 'GET_LEAD_HISTORY'
export const GET_ENQUIRER_NOTIFICATION = 'GET_ENQUIRER_NOTIFICATION'
export const GET_LEAD_ORG_NOTIFICATION = 'GET_LEAD_ORG_NOTIFICATION'
export const SAVE_SALE = 'SAVE_SALE'
export const FETCH_JOB_DETAILS = 'FETCH_JOB_DETAILS'
export const EDIT_JOB_DETAILS = 'EDIT_JOB_DETAILS'
export const SAVE_JOB_DETAILS = 'SAVE_JOB_DETAILS'
export const DELETE_JOB_DETAILS = 'DELETE_JOB_DETAILS'
export const DIALOG_STATE = 'DIALOG_STATE'
export const SET_REASSIGN_FIELDS = 'SET_REASSIGN_FIELDS'
export const REASSIGN_LEAD = 'REASSIGN_LEAD'
export const SEND_ENQUIRER_MESSAGE = 'SEND_ENQUIRER_MESSAGE'
export const GET_ORGANIZATION_POSTCODE_FILTERED = 'GET_ORGANIZATION_POSTCODE_FILTERED'
export const SAVE_ESCALATION_METERS = 'SAVE_ESCALATION_METERS'
export const ASSIGN_USER_TO_LEAD = 'ASSIGN_USER_TO_LEAD'
export const FETCH_ASSIGNED_USERS = 'FETCH_ASSIGNED_USERS'
export const REMOVE_ASSIGNED_USER = 'REMOVE_ASSIGNED_USER'
export const ADD_ASSIGNED_USER = 'ADD_ASSIGNED_USER'
export const SET_DYNAMIC_VALIDATION_RULE = 'SET_DYNAMIC_VALIDATION_RULE'
export const SET_DYNAMIC_VALIDATION_RULE_2 = 'SET_DYNAMIC_VALIDATION_RULE_2'
export const SET_ENQUIRY_DETAILS_DYNAMIC_VALIDATION_RULE = 'SET_ENQUIRY_DETAILS_DYNAMIC_VALIDATION_RULE'
export const SET_ENQUIRY_DETAILS_DYNAMIC_VALIDATION_RULE_2 = 'SET_ENQUIRY_DETAILS_DYNAMIC_VALIDATION_RULE_2'
export const LEAD_OVERVIEW = 'LEAD_OVERVIEW'
export const LEAD_OVERVIEW_NESTED = 'LEAD_OVERVIEW_NESTED'


// leadassign.js
export const GET_ASSIGNED_USERS = 'GET_ASSIGNED_USERS'
export const ASSIGN_USER_INTO_LEAD = 'ASSIGN_USER_INTO_LEAD'
export const INSERT_ASSIGNED_USER = 'INSERT_ASSIGNED_USER'
export const DELETE_ASSIGNED_USER = 'DELETE_ASSIGNED_USER'
export const SET_LEAD_DATA = 'SET_LEAD_DATA'

// orgnanisations.js
export const FETCH_ORGANISATION = 'FETCH_ORGANISATION'
export const FETCH_ORGANISATIONS = 'FETCH_ORGANISATIONS'
export const EDIT_ORGANISATION = 'EDIT_ORGANISATION'
export const SAVE_ORGANISATION = 'SAVE_ORGANISATION'
export const DELETE_ORGANISATION = 'DELETE_ORGANISATION'
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_POSTCODE_IMPORT = 'FETCH_POSTCODE_IMPORT'
export const FETCH_ORGANISATION_POSTCODES = 'FETCH_ORGANISATION_POSTCODES'
export const FETCH_FILTER_ORGANISATION = 'FETCH_FILTER_ORGANISATION'
export const FETCH_ORG_COMMENTS = 'FETCH_ORG_COMMENTS'
export const ADD_ORG_COMMENT = 'ADD_ORG_COMMENT'
export const DELETE_ORG_COMMENT = 'DELETE_ORG_COMMENT'
export const EDIT_ORG_COMMENT = 'EDIT_ORG_COMMENT'
export const CLOSE_SUSPENDED_MODAL = 'CLOSE_SUSPENDED_MODAL'
export const CLOSE_NOTICE_MODAL = 'CLOSE_NOTICE_MODAL'
export const FETCH_ORG_SYSTEM_ACTIVITY = 'FETCH_ORG_SYSTEM_ACTIVITY'
export const FETCH_ORG_POSTCODES = 'FETCH_ORG_POSTCODES'
export const FILTER_SYSTEM_ACTIVITIES = "FILTER_SYSTEM_ACTIVITIES";
export const GET_CURRENT_LEADS = 'GET_CURRENT_LEADS'
export const UPDATE_AVAILABILITY = 'UPDATE_AVAILABILITY'
export const GET_REASSIGNED_LEADS = 'GET_REASSIGNED_LEADS'
export const ORGANISATION_OVERVIEW = 'ORGANISATION_OVERVIEW'
export const GET_ORGANISATION_LEAD_STATS = 'GET_ORGANISATION_LEAD_STATS'


// users.js
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
export const FETCH_USERS = 'FETCH_USERS'
export const SAVE_USER = 'SAVE_USER'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USERS = 'DELETE_USERS'
export const EDIT_USER = 'EDIT_USER'
export const GET_USER = 'GET_USER'
export const CLEAR_USER_FORM = 'CLEAR_USER_FORM'
export const SAVE_USER_FAILED = 'SAVE_USER_FAILED'

// settings.js
export const FETCH_SETTINGS = 'FETCH_SETTINGS'
export const SAVE_SETTINGS = 'SAVE_SETTINGS'
export const DELETE_SETTINGS = 'DELETE_SETTINGS'
export const EDIT_SETTINGS = 'EDIT_SETTINGS'
export const GET_SETTINGS = 'GET_SETTINGS'
export const GET_SETTING = 'GET_SETTING'
export const SET_SETTINGS_ERRORS = 'SET_SETTINGS_ERRORS'
export const CLEAR_SETTINGS_ERRORS = 'CLEAR_SETTINGS_ERRORS'
export const DIALOG_SETTINGS_STATE = 'DIALOG_SETTINGS_STATE'
export const SETTING_COMPANY_NAME = 'SETTING_COMPANY_NAME'

// roles.js
export const FETCH_ROLES = 'FETCH_ROLES'
export const EDIT_ROLE = 'EDIT_ROLE'
export const SAVE_ROLE = 'SAVE_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
export const DIALOG_ROLE_STATE = 'DIALOG_ROLE_STATE'

// permissions.js
export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS'
export const ADD_PERMISSION = 'ADD_PERMISSION'
export const REMOVE_PERMISSION = 'REMOVE_PERMISSION'
export const SHOW_PERMISSION_INPUT = 'SHOW_PERMISSION_INPUT'

// orglocators.js
export const SAVE_ORG_LOCATOR = 'SAVE_ORG_LOCATOR'
export const FETCH_ORG_LOCATOR = 'FETCH_ORG_LOCATOR'
export const GET_ORG_LOCATOR = 'GET_ORG_LOCATOR'
export const EDIT_ORG_LOCATOR = 'EDIT_ORG_LOCATOR'
export const DELETE_ORG_LOCATOR = 'DELETE_ORG_LOCATOR'
export const IMPORT_ORG_LOCATOR = 'IMPORT_ORG_LOCATOR'

// activitylogs.js
export const FETCH_ACTIVITY_LOGS = 'FETCH_ACTIVITY_LOGS'
export const FETCH_ACTIVITY_EMAIL_DATA = 'FETCH_ACTIVITY_EMAIL_DATA'
export const FETCH_MORE_ACTIVITY_LOGS = 'FETCH_MORE_ACTIVITY_LOGS'

// notifications.js
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const FETCH_UNREAD_NOTIFICATIONS = 'FETCH_UNREAD_NOTIFICATIONS'
export const READ_NOTIFICATION = 'READ_NOTIFICATION'
export const READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION'
export const FETCH_LOAD_MORE_NOTIFICATION = 'FETCH_LOAD_MORE_NOTIFICATION'
export const SHOW_OOUTGOING_MODAL = 'SHOW_OOUTGOING_MODAL'

// report.js
export const FETCH_ADVERTISING_MEDIUM = 'FETCH_ADVERTISING_MEDIUM'
export const FETCH_ORGANISATION_STATUS = 'FETCH_ORGANISATION_STATUS'
export const FETCH_LEADS_WON = 'FETCH_LEADS_WON'

// dashboard.js
export const FETCH_LEADS_DASHBOARD = 'FETCH_LEADS_DASHBOARD'

// leadjobs.js
export const FETCH_LEAD_JOBS = 'FETCH_LEAD_JOBS'
export const FETCH_LEAD_JOB = 'FETCH_LEAD_JOB'
export const FETCH_LEAD_JOB_TOTAL_SALES = 'FETCH_LEAD_JOB_TOTAL_SALES'

// profile.js
export const SAVE_PROFILE = 'SAVE_PROFILE'
export const FETCH_PROFILE = 'FETCH_PROFILE'

// leadescalation.js
export const SHOW_ESCALATION = 'SHOW_ESCALATION'
export const UPDATE_ESCALATION = 'UPDATE_ESCALATION'
export const CHANGE_RULES = 'CHANGE_RULES'
export const SET_ICON_FORM = 'SET_ICON_FORM'
export const SET_ICON_FORM_TYPE = 'SET_ICON_FORM_TYPE'

// stats.js
export const FETCH_LEAD_STATS = 'FETCH_LEAD_STATS'
export const FETCH_ORGANIZATION_STATS = 'FETCH_ORGANIZATION_STATS'

// timesettings.js
export const FETCH_TIME_SETTINGS = 'FETCH_TIME_SETTINGS'
export const SAVE_TIME_SETTING = 'SAVE_TIME_SETTING'
export const EDIT_TIME_SETTING = 'EDIT_TIME_SETTING'
export const DELETE_TIME_SETTING = 'DELETE_TIME_SETTING'
export const CLEAR_TIME_SETTING_FORM = 'CLEAR_TIME_SETTING_FORM'
export const CHANGE_TIME_SETTING_RULES = 'CHANGE_TIME_SETTING_RULES'

// orgcompare.js
export const FETCH_LEAD_ORG_POST_CODES = 'FETCH_LEAD_ORG_POST_CODES'

// orghistory.js
export const FETCH_ORG_NOTIFICATION_HISTORY = 'FETCH_ORG_NOTIFICATION_HISTORY'
export const SEND_ORG_MESSAGE = 'SEND_ORG_MESSAGE'

// customer.js
export const GET_CUSTOMERS = 'GET_CUSTOMERS'

// scrum
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_STATUS = 'FETCH_STATUS'
export const SAVE_TASK = 'SAVE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS'
export const GET_ASSIGNED_TASK_USERS = 'GET_ASSIGNED_TASK_USERS'

// stores.js
export const GET_STORES = 'GET_STORES'
export const SAVE_STORE = 'SAVE_STORE'
export const SHOW_STORES = 'SHOW_STORES'
export const SAVE_STORES = 'SAVE_STORES'
export const DELETE_STORES = 'DELETE_STORES'
export const GET_HISTORIES = 'GET_HISTORIES'
export const GET_STORES_LOGS = 'GET_STORES_LOGS'
