@component('mail::message', ['custom_header_logo' => $data['custom_logo'] ?? ''])
# Leaf Stopper Leads Update Request

Dear <b>{{$data['organisation_name']}}</b>,

Our records show that one or more leads allocated to you are pending and have not been closed-off.

Please reply to this email with Lead Status information so we can update our records.

<b>NOTE</b> - If the Lead has been WON & INSTALLED, please include the following in your update:

How many metres of Gutter Edge<br>
How many metres of Valley<br>
Date of installation.<br>

<b style="color: #DE1F21">{{count($data['leads'])}} Current Leads</b>

@foreach($data['leads'] as $lead)
  <b>{{ trans('email.lead_id') }}#</b> <b style="color: #117EE7">{{ $lead['lead_id'] }}</b> <br>
  {{ trans('email.inquirer_name') }}: {{ $lead['enquirer'] }} <br>
  {{ trans('email.inquirer_contact_number') }}: {{ $lead['contact_number'] }} <br>
  {{ trans('email.inquirer_address') }}: {{ $lead['address'] }} <br>

  <b>Update Lead ID#<span style="color: #117EE7">{{ $lead['lead_id'] }}</span></b> <br><br>

  ____________________________________________________________________ <br><br><br>
@endforeach

NOTE: This Update Request will be sent out weekly while there are leads pending.

You also have the option to log into the Traleado portal to make your own updates by visiting www.traleado.com .

If you have forgotten or do not know your password please contact Administration on 1300 334 333. <br>

Regards, <br>
Leaf Stopper Team <br>
(This email was generated by Traleado)
@endcomponent
